### ISSUE TITLE
Add custom shortcuts / commands line

### ISSUE THREAD

**Issue by iccuramgh** [mmaximo33/EFDE#43]
## Feature Description

The objective of this proposal is to add the possibility of incorporating custom commands. 

It would be interesting if it could be created at a global level and at a project level. 

- Project lvl ~/path/project/.efde/commands/customaction.bash
- Global lvl ~/.efde/custom_cli/customaction.bash

That can be executed by shortcut

```
efde custom:command:line
efde ccli:customaction
```

**Comment by mmaximo33** [comment]
[See documentation ](https://github.com/mmaximo33/EFDE/blob/c315a1369aad8432052feb16b68d5e78804b3bb2/docs/implemention.md#custom-shortcuts)
